version: "3"

services:
  mysql:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      # gorm can struct->automigrate as well
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/mount:/var/lib/mysql
    environment:
      MYSQL_DATABASE: challenge_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  # docs:
  #   container_name: docs
  #   build:
  #     context: .
  #     dockerfile: ./docker/docs/Dockerfile
  #   environment:
  #     API_URL: swagger/openapi.yaml
  #   ports:
  #     - '8081:8080'
  #   volumes:
  #     - ./docs:/usr/share/nginx/html/swagger

  api-server:
    container_name: api-server
    build:
      context: .
      dockerfile: ./Dockerfile
    # image: vedaga/scjty8s4erci:0.2.0
    ports:
      - "3030:3030"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DBNAME: challenge_db
      GOMAXPROCS: 4
    tty: true
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    